articles/urls.py
from django.urls import path

from articles import views

urlpatterns = [
    path('', views.ArticlesListView.as_view(), name='all_articles'),
    path('delete/<int:pk>', views.ArticleDelete.as_view(), name='article_delete'),
    path('create/', views.ArticleCreate.as_view(), name='new_article'),
    path('edit/<int:pk>', views.ArticleUpdate.as_view(), name='edit_article'),
    path('about_us', views.ProtectedTemplateView.as_view(template_name='articles/about.html'), name='about_us'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category_detail'),
    path('<int:article_id>/like/', views.like_article, name='like_article'),
    path('<int:article_id>', views.article_by_id, name='article_by_id'),
    path('<slug:article_name>', views.article_by_name, name='article_by_name'),
    path('search/', views.search, name='article_search'),
]

news/urls.py
from django.contrib import admin
from django.urls import path, include, reverse, reverse_lazy
from django.views.generic import RedirectView

from articles import views

urlpatterns = [
    path('', views.index, name='homepage'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),
    path('about/', RedirectView.as_view(url='/articles/about_us')),
]

articles/models.py
import uuid as uuid
from django.db import models

from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        abstract = True


class Article(TimeStampModel):
    title = models.CharField(max_length=80)
    text = models.TextField()

    author = models.ForeignKey(USER_MODEL, on_delete=models.SET_NULL,
                               blank=True, null=True)
    channel = models.ForeignKey('Channel', on_delete=models.SET_NULL,
                                blank=True, null=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL,
                                 blank=True, null=True)
    tags = models.ManyToManyField('Tag')
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title}"

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.save()

    def add_like(self, user):
        like_exists = self.likes_set.filter(user=user).exists()
        if like_exists:
            self.likes_set.get(user=user, article_id=self.id).delete()
        else:
            self.likes_set.create(user=user, article=self)


class Channel(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.name}"


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.name}"


class Comment(TimeStampModel):
    text = models.CharField(max_length=256)
    author = models.ForeignKey(USER_MODEL, on_delete=models.SET_NULL,
                               blank=True, null=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.article}, {self.author}"


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    parent = models.ForeignKey('Category', blank=True,
                               null=True, on_delete=models.CASCADE, related_name='child_categories')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f"{self.name}"


class Likes(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)

articles/forms.py
from django.forms import ModelForm

from articles import models


class ArticleForm(ModelForm):
    class Meta:
        model = models.Article
        exclude = ('is_deleted', 'author', 'deleted_at')

articles/views.py
import datetime

from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, DetailView, ListView, DeleteView, CreateView, UpdateView

from articles import models, forms


class ProtectedTemplateView(UserPassesTestMixin, TemplateView):
    def test_func(self):
        return self.request.user.is_superuser

    def dispatch(self, request, *args, **kwargs):
        user_test_result = self.get_test_func()()
        if not user_test_result:
            return redirect('/')
        return super().dispatch(request, *args, **kwargs)


def index(request):
    articles = models.Article.objects.filter(is_deleted=False)
    categories = models.Category.objects.filter(parent__isnull=True).order_by('name')
    return render(request, 'articles/base.html',
                  {'categories': categories,
                   'articles': articles})


def article_by_name(request, article_name):
    now = datetime.datetime.now()
    return render(request, 'articles/article_by_name.html',
                  {'name': article_name,
                   'len': len(article_name),
                   'rendered': now})


def article_by_id(request, article_id):
    try:
        article = models.Article.objects.get(id=article_id)
    except (models.Article.DoesNotExist, models.Article.MultipleObjectsReturned):
        return redirect('/')
    return render(request, 'articles/article_by_id.html', {'article': article})


def search(request):
    # Get request value
    # Filter articles
    # Render page
    search = request.GET.get('search', '')
    articles = models.Article.objects.filter(title__icontains=search)
    return render(request, 'articles/search_result.html', {'articles': articles, 'search': search})


def like_article(request, article_id):
    # Dont scare this. It was just complicated example. lol
    article = models.Article.objects.get(id=article_id)
    if request.method == 'POST':
        article.add_like(request.user)
    return JsonResponse(dict(count=article.likes_set.count()))
    # return redirect(reverse('article_by_id', kwargs={"article_id": article_id}))


class CategoryDetailView(DetailView):
    model = models.Category
    context_object_name = 'category'


class ArticlesListView(ListView):
    model = models.Article
    queryset = models.Article.objects.filter(is_deleted=False)
    ordering = '-title'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        categories = models.Category.objects.all()
        context = super().get_context_data()
        context.update(dict(categories=categories))
        return context


class ArticleDelete(DeleteView):
    model = models.Article
    success_url = reverse_lazy('all_articles')


class ArticleCreate(CreateView):
    model = models.Article
    form_class = forms.ArticleForm
    success_url = reverse_lazy('all_articles')

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class ArticleUpdate(UpdateView):
    model = models.Article
    form_class = forms.ArticleForm
    success_url = reverse_lazy('all_articles')

articles/templates/articles/about.html
{% extends 'articles/base.html' %}


{% block title %}About us{% endblock %}

{% block content %}
    {% lorem 10 p %}
{% endblock %}

articles/templates/articles/article_by_id.html
{% extends 'articles/base.html' %}

{% block title %}{{ article_id }}{% endblock %}

{% block content %}
    <div class="container">
        {% include 'articles/includes/now.html' %}
        <h1>{{ article.title }}</h1>
        <div>{{ article.text }}</div>
        <hr/>
        Posted by: {{ article.author }} at {{ article.created_at }}
        <br/>
        {% if user.is_authenticated %}
            <form id="like_form" method="post">
                {% csrf_token %}
                <button type="submit " class="btn btn-danger">&#9829; <span
                        id="likes_count">{{ article.likes_set.count }}</span></button>
            </form>
        {% endif %}
    </div>

{% endblock %}

{% block extrajs %}
    <script type="text/javascript">
        {# Dont scare this. It was just complicated example. lol #}
        $(document).ready(
            $("#like_form").submit(function (e) {
                e.preventDefault();
                $.ajax(
                    {
                        type: 'POST',
                        url: '{% url 'like_article' article.id %}',
                        success: function (resp) {
                            $("#likes_count").html(resp.count);
                        }
                    }
                )
            }));
    </script>
{% endblock %}

articles/templates/articles/article_by_name.html
{% extends 'articles/base.html' %}
{% block content %}
    {% include 'articles/includes/now.html' with a='123456'%}
    Hi!
    <hr>
    I am article with name {{ name }}.
    {% if len > 10 %}
        Too long.
    {% elif len == 5 %}
        It's ok
    {% else %}
        {% if len == 1 %}
            Too short
        {% endif %}
    {% endif %}

{% endblock %}

articles/templates/articles/article_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

articles/templates/articles/article_form.html
{% extends 'articles/base.html' %}


{% block title %}Create article{% endblock %}

{% block content %}
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Save</button>
        </form>
    </div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'articles/base.html' %}


{% block title %}About us{% endblock %}

{% block content %}

    <p><a class="btn btn-info" href="{% url 'new_article' %}">Add new article</a></p>
    <div class="row">
        <div class="col-3">        {% for category in categories %}
            <li>
                {{ category.name }}
                {% if category.child_categories.all %}
                    <ul>{% for subcategory in category.child_categories.all %}
                        <li>{{ subcategory }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endfor %}
        </div>
        <div class="col-5">   {% for article in article_list.all %}
            <p><a href="{% url 'article_by_id' article.id %}">{{ article.title }}</a></p>
            <small>{{ article.text | truncatechars:100 }}</small>
            {% if user.is_superuser %}
                <form action="{% url 'article_delete' article.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-small btn-warning">Delete</button>
                </form>

                <a href="{% url 'article_delete' article.id %}" class="btn btn-small btn-danger">Delete</a>
                {% if user == article.author or user.is_superuser %}<a href="{% url 'edit_article' article.id %}">Edit</a>
                {% endif %}
            {% endif %}
            {% if not forloop.last %}
                <hr style="border-top: 1px solid rgb(66,66,66)"/>{% endif %}
        {% empty %}
            no articles
        {% endfor %}
            <br/>
            {% include 'articles/includes/pagination.html' %}
        </div>
    </div>
{% endblock %}

articles/templates/articles/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
        .hr {

        }
    </style>
    <title>NEWS | {% block title %}HOME{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {#    <a class="navbar-brand" href="#">Navbar</a>#}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'article_by_id' article_id=11 %}">Article by id</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{ user }}</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'article_search' %}">
            <input class="form-control mr-sm-2"
                   type="search"
                   name="search"
                   value="{% if search %}{{ search }}{% endif %}"
                   placeholder="Search"
                   aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% if user.is_authenticated %}
            <ul class="navbar-nav mr-5">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a> |
            <a class="nav-link" href="{% url 'register' %}">Register</a>
        {% endif %}
    </div>
</nav>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% block content %}
    <h4>Categories</h4>
    <ul>
        {% for category in categories %}
            <li>
                {{ category.name }}
                {% if category.child_categories.all %}
                    <ul>{% for subcategory in category.child_categories.all %}
                        <li>{{ subcategory }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <hr>


{% endblock %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
{% block extrajs %}
{% endblock %}
</body>
</html>

articles/templates/articles/category_detail.html
{% extends 'articles/base.html' %}


{% block title %}About us{% endblock %}

{% block content %}
    {{ category.name }}
    {% if category.child_categories.all %}
        <ul>{% for subcategory in category.child_categories.all %}
            <li><a href="{% url 'category_detail' subcategory.id %}">{{ subcategory }}</a></li>
        {% endfor %}
        </ul>
    {% endif %}
    <br>
    {% for article in category.article_set.all %}
        {{ article.title }}
    {% empty %}
        no articles
    {% endfor %}
{% endblock %}

articles/templates/articles/search_result.html
{% extends 'articles/base.html' %}


{% block title %}Search{% endblock %}

{% block content %}
    <div class="container">
        {% if articles|length > 0 %} Search results for: {{ search }} {% endif %}
        {% for article in articles %}
            <p><a href="{% url 'article_by_id' article.id %}">{{ article.title }}</a></p>
            <small>{{ article.text | truncatechars:100 }}</small>
            {% if not forloop.last %}
                <hr style="border-top: 1px solid rgb(66,66,66)"/>{% endif %}
        {% empty %}
            No articles :C
        {% endfor %}</div>
{% endblock %}